### ISSUE TITLE
是否有插件可以使radarr用pikpak当下载器呢？

### ISSUE THREAD

**Issue by lssb** [ykxVK8yL5L/jellyfin-plugin-pikpak#1]
我的想法是把种子或磁力传给pikpak去离线，然后用aria2取回，是否有类似的插件或者是否有写类似插件的指导？

**Comment by ykxVK8yL5L** [comment]
> 我的想法是把种子或磁力传给pikpak去离线，然后用aria2取回，是否有类似的插件或者是否有写类似插件的指导？

不太明白什么意思，要看你具体的操作流程了  目前主流的操作都是你这样的操作思路。 你可以试下用Alist挂载pikpak，然后网页端添加磁力离线，在alist上使用aria2下载到本地。

**Comment by lssb** [comment]
没想到这么久了还是被回复了，
、
我已经写脚本实现这个操作了，但是现在的问题是aria2从pikpak取回的失败率有点高

alist有web api应该也可以实现自动化， 但是还没有尝试

部分资源用alist也会失败，无法取回， 目前感觉从pikpak取回最快最稳的还是pikpak自己的客户端

**Comment by ykxVK8yL5L** [comment]
> 没想到这么久了还是被回复了， 、 我已经写脚本实现这个操作了，但是现在的问题是aria2从pikpak取回的失败率有点高
> 
> alist有web api应该也可以实现自动化， 但是还没有尝试
> 
> 部分资源用alist也会失败，无法取回， 目前感觉从pikpak取回最快最稳的还是pikpak自己的客户端

抱歉 不怎么看issues. 可以进群交流. pikpak用aria2下载速度相当不错的 我没遇到过失败的问题. 可能你宽带运营商限制或走代理的问题吧. 建议你看下我github actions转阿里云的方法. 稳得狠.

**Comment by lssb** [comment]
> > 没想到这么久了还是被回复了， 、 我已经写脚本实现这个操作了，但是现在的问题是aria2从pikpak取回的失败率有点高
> > alist有web api应该也可以实现自动化， 但是还没有尝试
> > 部分资源用alist也会失败，无法取回， 目前感觉从pikpak取回最快最稳的还是pikpak自己的客户端
> 
> 抱歉 不怎么看issues. 可以进群交流. pikpak用aria2下载速度相当不错的 我没遇到过失败的问题. 可能你宽带运营商限制或走代理的问题吧. 建议你看下我github actions转阿里云的方法. 稳得狠.

确实是走了代理的原因，感谢指导

**Comment by ykxVK8yL5L** [comment]
> > > 没想到这么久了还是被回复了， 、 我已经写脚本实现这个操作了，但是现在的问题是aria2从pikpak取回的失败率有点高
> > > alist有web api应该也可以实现自动化， 但是还没有尝试
> > > 部分资源用alist也会失败，无法取回， 目前感觉从pikpak取回最快最稳的还是pikpak自己的客户端
> > 
> > 
> > 抱歉 不怎么看issues. 可以进群交流. pikpak用aria2下载速度相当不错的 我没遇到过失败的问题. 可能你宽带运营商限制或走代理的问题吧. 建议你看下我github actions转阿里云的方法. 稳得狠.
> 
> 确实是走了代理的原因，感谢指导

欢迎交流反馈😊
